<?php

namespace ContainerW4xSFlQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiErrorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ApiErrorController' shared autowired service.
     *
     * @return \App\Controller\ApiErrorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiErrorController.php';

        $container->services['App\\Controller\\ApiErrorController'] = $instance = new \App\Controller\ApiErrorController();

        $instance->setContainer(($container->privates['.service_locator.x9zd309'] ?? $container->load('get_ServiceLocator_X9zd309Service'))->withContext('App\\Controller\\ApiErrorController', $container));

        return $instance;
    }
}
