# config/services.yaml
parameters:
    # Configuration JWT
    jwt.secret: '%env(JWT_SECRET)%'
    jwt.ttl: '%env(JWT_TTL)%'
    app.jwt.secret: '%env(string:JWT_SECRET)%'
    app.jwt.ttl: '%env(int:JWT_TTL)%'
    env(EMAIL_RECEIVER): '%env(resolve:EMAIL_RECEIVER)%'
    env(EMAIL_SENDER): '%env(resolve:EMAIL_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $jwtSecret: '%app.jwt.secret%'
            int $jwtTtl: '%app.jwt.ttl%'

    App\Service\JwtService:
        arguments:
            $secret: '%jwt.secret%'
            $ttl: '%jwt.ttl%'
        autowire: false 

    App\EventListener\ExceptionListener:
        arguments:
            $httpClient: '@http_client'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'