# config/services.yaml
parameters:
    mail_dsn: '%env(MAILER_DSN)%'
    app.email.receiver: '%env(resolve:EMAIL_RECEIVER)%'
    app.email.sender: '%env(resolve:EMAIL_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $emailSender: '%app.email.sender%'
            string $emailReceiver: '%app.email.receiver%'
     

    App\EventListener\ExceptionListener:
        arguments:
            $httpClient: '@http_client'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Service\ReportGeneratorService:
        arguments: []

    App\Service\SendMailService:
        arguments:
            $mailer: '@mailer.mailer'
            $emailSender: '%env(EMAIL_SENDER)%'
            $emailReceiver: '%env(EMAIL_RECEIVER)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'