<?php

namespace ContainerEw6Z4sR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ExceptionListener' shared autowired service.
     *
     * @return \App\EventListener\ExceptionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/ExceptionListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\ExceptionListener'])) {
            return $container->privates['App\\EventListener\\ExceptionListener'];
        }
        $b = ($container->privates['App\\Service\\SendMailService'] ?? $container->load('getSendMailServiceService'));

        if (isset($container->privates['App\\EventListener\\ExceptionListener'])) {
            return $container->privates['App\\EventListener\\ExceptionListener'];
        }

        return $container->privates['App\\EventListener\\ExceptionListener'] = new \App\EventListener\ExceptionListener($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), $b);
    }
}
