<?php

namespace ContainerEw6Z4sR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManageUserCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ManageUserCommand' shared autowired service.
     *
     * @return \App\Command\ManageUserCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ManageUserCommand.php';

        $container->privates['App\\Command\\ManageUserCommand'] = $instance = new \App\Command\ManageUserCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:manage-user');
        $instance->setDescription('Crée ou modifie un utilisateur avec login (email/téléphone) et statut actif/inactif');

        return $instance;
    }
}
