<?php

namespace ContainerEw6Z4sR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManageUserCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ManageUserCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ManageUserCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:manage-user', [], 'Crée ou modifie un utilisateur avec login (email/téléphone) et statut actif/inactif', false, #[\Closure(name: 'App\\Command\\ManageUserCommand')] fn (): \App\Command\ManageUserCommand => ($container->privates['App\\Command\\ManageUserCommand'] ?? $container->load('getManageUserCommandService')));
    }
}
