<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEw6Z4sR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEw6Z4sR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEw6Z4sR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEw6Z4sR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEw6Z4sR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ew6Z4sR',
    'container.build_id' => '27c1653c',
    'container.build_time' => 1755212158,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEw6Z4sR');
