<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxtovik\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxtovik/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKxtovik.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKxtovik\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKxtovik\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kxtovik',
    'container.build_id' => 'cfef348e',
    'container.build_time' => 1755697089,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxtovik');
